services:
  db:
    image: postgres:17
    container_name: cinebook_db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: cinebook_db
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U username"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: cinebook_backend
    restart: always
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    environment:
      - DATABASE_URL=postgres://username:password@db:5432/cinebook_db
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./frontend
    container_name: cinebook_frontend
    restart: always
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    command: npm run dev
    depends_on:
      - backend

volumes:
  postgres_data: