FROM python:3.13-alpine

# Set the working directory in the container
WORKDIR /app

# Install build dependencies for psycopg2-binary
RUN apk add --no-cache postgresql-dev build-base

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code into the container
COPY . .

# Expose port 8000 to the outside world
EXPOSE 8000

# Run the Django server
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]