# Generated by Django 5.2.6 on 2025-09-24 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('synopsis', models.TextField()),
                ('category', models.CharField(choices=[('ACTION', 'Action'), ('COMEDY', 'Comedy'), ('DRAMA', 'Drama'), ('HORROR', 'Horror'), ('SCIFI', 'Sci-Fi'), ('THRILLER', 'Thriller'), ('ROMANCE', 'Romance'), ('DOCUMENTARY', 'Documentary'), ('ANIMATION', 'Animation'), ('FANTASY', 'Fantasy'), ('MYSTERY', 'Mystery'), ('ADVENTURE', 'Adventure'), ('CRIME', 'Crime'), ('BIOGRAPHY', 'Biography'), ('HISTORY', 'History'), ('MUSICAL', 'Musical'), ('WAR', 'War'), ('WESTERN', 'Western'), ('SPORTS', 'Sports'), ('FAMILY', 'Family'), ('OTHER', 'Other')], default='ACTION', max_length=50)),
                ('director', models.CharField(max_length=100)),
                ('producer', models.CharField(max_length=100)),
                ('trailer_url', models.URLField(blank=True)),
                ('trailer_pic_link', models.URLField(blank=True)),
                ('rating', models.CharField(choices=[('G', 'G'), ('PG', 'PG'), ('PG-13', 'PG-13'), ('R', 'R'), ('NC-17', 'NC-17'), ('UNRATED', 'Unrated'), ('NOT_RATED', 'Not Rated')], default='G', max_length=10)),
                ('is_running', models.BooleanField(default=False)),
                ('is_coming_soon', models.BooleanField(default=False)),
                ('poster_image_url', models.URLField(blank=True)),
                ('cast', models.ManyToManyField(to='core.actor')),
            ],
        ),
        migrations.CreateModel(
            name='Showtime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showtimes', to='core.movie')),
            ],
        ),
    ]
